### ISSUE TITLE
FCAL Shower output

### ISSUE THREAD

**Issue by beattite** [rjones30/HDGeant4#2]
Justin, Dave, and I were looking at a comparison between HDGeant3 and 4.  We simulated a signal MC data set with Simon's genEtaRegge generator (eta -> 2g).

We ran it with the same control.in file (1000 events) through HDG3 and HDG4.  We noticed a much larger number of reconstructed neutral showers in the HDG4 version.  This can be seen quickly by looking at an hd_dump output.  An example output from HDG3 and HDG4 for the same generated event can be seen at [GlueX-doc-3188](http://argus.phys.uregina.ca/cgi-bin/private/DocDB/ShowDocument?docid=3188).  From the hd_dump output, one can also see that the shower time is different between 3 and 4 (I didn't look into the code, maybe this is intentional), and for most of the events generated, both photons land in the FCAL.  As far as I can tell, this is just an FCAL clustering problem, but I didn't look at many events with photons landing in the BCAL, so I'm not entirely sure the issue doesn't extend to the BCAL.

The .pdf files in [GlueX-doc-3188](http://argus.phys.uregina.ca/cgi-bin/private/DocDB/ShowDocument?docid=3188) are histograms of the number of neutral showers (left) and charged track hypotheses (right) in the events for HDG3 and HDG4.  Indeed, we see an average of 6 - 7 neutral showers rather than the expected 2 that we see with HDG3.

The genEtaRegge file we used for this is at /work/halld/beattite/BReta/DEC4gg9GeV.hddm
The control.in file is at /work/halld/beattite/BReta/G4/control.in
The HDG3 output file is at /work/halld/beattite/BReta/DEC4gg9GeVhdgeant_smeared.hddm
The HDG4 output file is at /work/halld/beattite/BReta/G4/fileG4gg_smeared.hddm (I think)

**Comment by rjones30** [comment]
A lot of work has been done on the simulation of showers in HDGeant4 since this report was first issued. Can you have a look now and see if things have improved?
